### ISSUE TITLE
Disable this on large file?

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/nvim-treesitter-context#14]
NVIM becomes laggy when opened with a large file. How to disable this plugin when this happens?

**Comment by syphar** [comment]
Have you tried removing this plugin to see if it is actually the reason for the lag? 

From my experience lag with big files often comes from treesitter parsing itself.

**Comment by nyngwang** [comment]
> Have you tried removing this plugin to see if it is actually the reason for the lag?

@syphar Oops, I have done this before I noticed your comment. just found that the culprit is another plugin called https://github.com/petertriho/nvim-scrollbar.

Would you mind sharing how do you deal with large files (>10,000 lines) for NeoVim? Mine, which I referenced the answer https://vi.stackexchange.com/a/169/41775:

```lua
-- These options seems to not make much differences so got commented out. But I still put them here for reference.
-- \ setlocal eventignore+=FileType |
-- \ setlocal eventignore+=CursorMove |
-- \ setlocal eventignore+=CursorHold |
-- \ setlocal eventignore+=DiagnosticChanged |
-- \ setlocal eventignore+=BufReadPre |
-- \ setlocal eventignore+=BufRead |
-- \ setlocal eventignore+=BufWinEnter |
-- \ setlocal eventignore+=WinEnter |
-- \ setlocal eventignore+=WinScrolled |
-- \ setlocal eventignore+=treesitter_context |
-- \ setlocal eventignore+=treesitter_context_update |
vim.cmd([[
  augroup LargeFile
    au!
    au BufReadPre *
    \ if getbufinfo(bufnr())[0].linecount > 2000 |
      \ setlocal noswapfile bufhidden=unload buftype=nowrite undolevels=-1 |
    \ endif
  augroup END
]])
```

While there is another kind of issue that depends on how one would define a "large file". For example, I currently cannot solve this same issue with (front-end) minified `js`-files (files with any **_long column_** > 1000). For this situation, I still don't have a solution, yet.

**Comment by nyngwang** [comment]
@syphar: you might want to take a look at my edit! (Sorry for possible annoying, but this one is the last ping.)

**Comment by syphar** [comment]
I disable treesitter for these too: 
https://www.reddit.com/r/neovim/comments/s9kdsm/disable_treesitter_for_files_larger_than_x_lines/

https://github.com/nvim-treesitter/nvim-treesitter/blob/16c773c0f826785760dce92bf713fb7e8e19e70c/doc/nvim-treesitter.txt#L108-L124

Apart from that, I rarely have files so big that this would be an issue.

**Comment by lewis6991** [comment]
This old vim plugin might be worth looking into: https://github.com/vim-scripts/LargeFile
