### ISSUE TITLE
Merged into a single line if the value of a field is a function definition in a Lua table

### ISSUE THREAD

**Issue by rockyzhang24** [lewis6991/nvim-treesitter-context#19]
Take this piece of code, `nvim-treesitter-context` default config, as an example
```lua
require 'treesitter-context'.setup {
  enable = true,
  throttle = true,
  max_lines = 0,
  -- Match patterns for TS nodes.
  patterns = {
    default = {
      'class',
      'function',
      'method',
      'for',
      'while',
      'if',
      'switch',
      'case',
    },
    -- rust = {
    --   'impl_item',
    -- },
  },
  exact_patterns = {
    -- Example for a specific filetype with Lua patterns
    -- Treat patterns.rust as a Lua pattern (i.e "^impl_item$" will
    -- exactly match "impl_item" only)
    -- rust = true,
  }
}
```

The value of each field is not function definition, so the context is shown as normal. 
<img width="1679" alt="Screen Shot 2022-05-06 at 15 33 52" src="https://user-images.githubusercontent.com/11582667/167224349-b9180fe9-14b1-4ee7-a466-230a16edeac6.png">

Then I add a filed at the end of the table whose value is a function definition, like below
```lua
require 'treesitter-context'.setup {
  enable = true,
  throttle = true,
  max_lines = 0,
  -- Match patterns for TS nodes.
  patterns = {
    default = {
      'class',
      'function',
      'method',
      'for',
      'while',
      'if',
      'switch',
      'case',
    },
    -- rust = {
    --   'impl_item',
    -- },
  },
  exact_patterns = {
    -- Example for a specific filetype with Lua patterns
    -- Treat patterns.rust as a Lua pattern (i.e "^impl_item$" will
    -- exactly match "impl_item" only)
    -- rust = true,
  }

  key1 = function()
  end
}
```

The context gets an abnormal behavior, i.e., all lines are merged into a single line shown in the context window. See the screenshot below

<img width="1679" alt="Screen Shot 2022-05-06 at 15 38 38" src="https://user-images.githubusercontent.com/11582667/167224822-e5756e06-a151-4e01-98f4-43616c31d6af.png">

Thank you very much.

**Comment by syphar** [comment]
This is actually a feature going rogue. 

When you have a function call with arguments but formatted in multiple lines, then treesitter-context will merge these lines into one line so you see the function arguments in the context. 

https://github.com/lewis6991/nvim-treesitter-context/blob/28fd8fea0d056333dcd3cd5abcb1256e3e526417/lua/treesitter-context.lua#L25-L35

**Comment by lewis6991** [comment]
Issue now in upstream https://github.com/nvim-treesitter/nvim-treesitter-context/issues/116
