### ISSUE TITLE
Make floating window's `zindex` configurable

### ISSUE THREAD

**Issue by b0o** [lewis6991/nvim-treesitter-context#20]
It would be nice if the `zindex` option of `nvim_open_win()` was configurable through this plugin's options.

**Comment by lewis6991** [comment]
What's the use case?

**Comment by b0o** [comment]
There are many plugins nowadays utilizing floating windows, and often the user has some preference as to the stacking order if windows happen to overlap. 

For example, I'd always like for my [Incline statusline](https://github.com/b0o/incline.nvim) to appear above the TSContext window, but below Telescope windows. Incline allows its zindex to be configured, but since neither Telescope nor this plugin allow it, and since they both use Neovim's default zindex of 50, I can't achieve this.

Ideally, I would set:

```
tscontext.zindex = 40
incline.zindex = 50
telescope.zindex = 60
```

I've opened an issue with a similar request for Telescope: https://github.com/nvim-telescope/telescope.nvim/issues/1926

In my opinion, plugins should (almost) always allow the zindex of their floating windows to be configured, unless there's a good reason not to.

**Comment by lewis6991** [comment]
> For example, I'd always like for my [Incline statusline](https://github.com/b0o/incline.nvim) to appear above the TSContext window, but below Telescope windows. Incline allows its zindex to be configured, but since neither Telescope nor this plugin allow it, and since they both use Neovim's default zindex of 50, I can't achieve this.

Sounds like an [XY problem](https://en.wikipedia.org/wiki/XY_problem) to me.

You would almost never want any popup window to appear above Telescope and you want almost never want any popup below a TSContext window. Incline statusline sits inbetween.

The actual fix here is for TSContext to set a much lower value for `zindex`, and additionally for telescope to set a higher value than default. I think the default of `50` is appropriate for things like LSP hover or Gitsigns preview, so therefore, Incline status should set a default value higher than `50`.

> In my opinion, plugins should (almost) always allow the zindex of their floating windows to be configured, unless there's a good reason not to.

This is (IMO) over-configuration. This isn't something users should ever be concerned about, especially for this situation. It is simple and harmless to expose it, but it should only ever be set in special situations where plugins are setting incorrect values.

I've opened https://github.com/neovim/neovim/issues/18486 so more guidance can be provided.

**Comment by b0o** [comment]
> I've opened https://github.com/neovim/neovim/issues/18486 so more guidance can be provided.

This is great. I fully agree that better guidance is needed.

> This isn't something users should ever be concerned about

Users should not care about the z-index per se, but they *do* care when a window they want to see is obscured by another one.

While better z-index guidance for plugin authors would do well to avoid the majority of issues, there are (IMO) too many different use cases for floating windows for us to be sure that a prescriptive approach would cover all bases.

Further, there is a matter of preference here. For instance, while it is true that Telescope should almost always appear above other floating windows, things are not so clear with regards to Incline & treesitter-context. I personally prefer Incline to appear above treesitter-context, but I do have a very large monitor with plenty of screen real estate. I could imagine the user of a small 11” laptop might prefer the opposite behavior. Incline already supports configuring its z-index, so this example is somewhat moot, but the point still stands with other combinations of plugins.

**Comment by lewis6991** [comment]
Done on upstream
