### ISSUE TITLE
Context lines should be disabled in special buffers like "q/"

### ISSUE THREAD

**Issue by xaljer** [lewis6991/nvim-treesitter-context#21]

**Comment by lewis6991** [comment]
What is a "q/" buffer?

**Comment by xaljer** [comment]
![图片](https://user-images.githubusercontent.com/8309631/167289261-8e5a51d9-7b5b-4640-82f9-dc4061c46674.png)

**Comment by lewis6991** [comment]
These buffers don't have treesitter highlighting

**Comment by xaljer** [comment]
![图片](https://user-images.githubusercontent.com/8309631/167289547-1764b54c-b7e9-4532-afce-89a1cfc7b509.png)

When I use the plugin without configuration in init.vim, if I type "q/", and context lines show on the buffer of the "q/" instead of the origin position.
But when I write the recommend configurations of README in my init.vim, it just works fine.

**Comment by lewis6991** [comment]
Ok. You should of started with that.
