### ISSUE TITLE
The line doesn't change now

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/nvim-treesitter-context#23]
As title. In short this plugin now just has a fixed-line shown on the top for each file.

at commit: c7b6db  
neovim version:

```
NVIM v0.8.0-dev+166-gc55867b46
Build type: Release
LuaJIT 2.1.0-beta3
```

The way to reproduce: Open any lua file with many indentations. Inside any lua object and make the field invisible from the top(so the nvim-treesitter-context should work like the DEMO from the video of the original one of the README made by romgrk). The topline doesn't change if I move the cursor in/out from the current indent level.

**Comment by lewis6991** [comment]
This isn't a useful issue report. Please provide more information, preferably with minimised testcase. Otherwise the issue will be closed.

**Comment by nyngwang** [comment]
I just reported the issue for the existing users. I have removed it because of this. You can close it if you want, but the bug exists. The only possible info I think relevant is my neovim version and the version of this plugin. Both have been added.

**Comment by lewis6991** [comment]
Your configuration. An example of text exhibiting the issue. Language. It's all relevant!

**Comment by nyngwang** [comment]
This is the configuration. The others can be found in my updated OP. I recommend you close this. Maybe it's just me who experienced this but I have removed it. I just assumed that this is an apparent bug (since it's apparent to me.)

```lua
use {
    'lewis6991/nvim-treesitter-context',
    requires = {
      'nvim-treesitter/nvim-treesitter'
    },
    config = function ()
      require('treesitter-context').setup {
        enable = true,
        throttle = true,
        max_lines = 1,
        patterns = {
          default = {
            'block',
            'arguments',
            'argument_list',
            'class',
            'field',
            'object',
            'method',
            'function',
            'func_literal',
            'if',
            'for',
            'while',
            'switch',
            'try',
            'except',
            'case',
          }
        }
      }
    end
  }
```

**Comment by lewis6991** [comment]
Your problem is that you have `max_lines` set to `1`.

**Comment by nyngwang** [comment]
But it used to work. And I don't need more than one line at the top.

**Comment by nyngwang** [comment]
Anyway let me close this for you.
