### ISSUE TITLE
treesitter-context.lua:443: attempt to index local 'query' (a nil value)

### ISSUE THREAD

**Issue by smartding** [lewis6991/nvim-treesitter-context#7]
After upgrading to latest nvim-treesitter/nvim-treesitter (commit id: 6f6cb206) and this plugin (commit id: e52e5ed9), now I have this error message whenever context is displayed:

```lua
Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...start/nvim-treesitter-context/lua/treesitter-context.lua:443: attempt to index local 'query' (a nil value)
stack traceback:
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:443: in function 'highlight_contexts'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:526: in function 'open'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:544: in function 'update_context'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:574: in function 'update'
        ...start/nvim-treesitter-context/lua/treesitter-context.lua:585: in function <...start/nvim-treesitter-context/lua/treesitter-context.lua:
583>
```

I'm using neovim at commit id: 3f2e9298bdd9, somewhere after 0.7 version

**Comment by lewis6991** [comment]
Sorry, doesn't happen for me. Can you provide a minimum testcase?

**Comment by megalithic** [comment]
Also seeing this; I JUST updated nvim to ensure I was at tip of `HEAD` to make sure there wasn't some update to nvim that you might perhaps hide the issue (most notably with treesitter things); also nvim-treesitter and all of my grammars are updated. 

My installed grammars: 

```lua
{
    "bash",
    "c",
    "cpp",
    "css",
    "comment",
    "dockerfile",
    "elixir",
    "elm",
    "erlang",
    "fish",
    "go",
    "graphql",
    "html",
    "heex",
    "javascript",
    "markdown",
    "jsdoc",
    "json",
    "jsonc",
    "lua",
    "make",
    "nix",
    "perl",
    "python",
    "query",
    "regex",
    "ruby",
    "rust",
    "scss",
    "surface",
    "toml",
    "tsx",
    "typescript",
    "yaml",
}
```

I'm able to consistently reproduce with bash scripts (treesitter grammar); here's the file I first noticed it on:

https://github.com/megalithic/dotfiles/blob/main/bin/paq-install

Simply scrolling up and down via repeated j/k navigation will trigger the exact error @smartding noted.

Barebones setup of nvim-treesitter-context is just plain old `require("treesitter-context").setup({})`.

Please let me know if there are _any_ other details I might provide to help troubleshoot.

**Comment by sheodox** [comment]
I've also had this happen. I don't have an example to share, but I was noticing it in .ts/.tsx files and it generally seemed to happen when I had function parameters spread over multiple lines and it was only partially off screen, something like this:

```typescript
function something(
    param1,
    param2,
    param3
) { 
```

I can't reproduce it now so I can't really give more details (I disabled the plugin for a while while I was encountering this so I don't remember exactly where I was seeing the error).

**Comment by smartding** [comment]
I notice the issue doesn't happen for lua, golang and c.
It only happens for bash scripts, and in @sheodox's case, also .ts/.tsx files

**Comment by lewis6991** [comment]
I was able to reproduce this in a bash file. Not fully sure what is happening but I've provided a workaround in #10. Can people review it?

**Comment by lewis6991** [comment]
Figured out the root cause. I wasn't mapping `neovim filetype` -> `treesitter language`, should be fixed now.

The original repo doesn't have this issue but does use private API's which is why I changed it.

**Comment by smartding** [comment]
It's working for bash scripts now.
Thanks.
